#!/bin/bash
if [ -z $1 ] || [ -z $2 ]; then
    echo 
    echo "USAGE: get-score username password"
    echo 
    exit 0;
fi
USERNAME=$1
PASSWORD=$2

curl http://stuach.sxu.edu.cn/student/checklogin.asp\?username\=$USERNAME\&password\=$PASSWORD -c cookies > /dev/null
curl http://stuach.sxu.edu.cn/student/achieve/achievebrow.asp -b cookies > result.html
